# Version catalog is a central place for you to declare and version dependencies
# https://docs.gradle.org/current/userguide/platforms.html#sub:version-catalog
# https://docs.gradle.org/current/userguide/platforms.html#sub::toml-dependencies-format

[versions]
kotlin = "2.4.20"
kotlinPoet = "2.4.0"
kspVersion = "2.3.12"
ktorVersion = "3.6.0"
arrowVersion = "2.2.3"
publishPluginVersion = "0.37.0"
swaggerAnnotationsVersion = "2.2.55"

[libraries]
# Code generation
kotlinPoet = { module = "com.squareup:kotlinpoet", version.ref = "kotlinPoet" }
kspApi = { module = "com.google.devtools.ksp:symbol-processing-api", version.ref = "kspVersion" }

#HTTP
ktor-server-core = { module = "io.ktor:ktor-server-core-jvm", version.ref = "ktorVersion" }
ktor-server-cio = { module = "io.ktor:ktor-server-cio-jvm", version.ref = "ktorVersion" }
ktor-server-status-pages = { module = "io.ktor:ktor-server-status-pages-jvm", version.ref = "ktorVersion" }
ktor-server-content-negotiation = { module = "io.ktor:ktor-server-content-negotiation-jvm", version.ref = "ktorVersion" }
ktor-client-content-negotiation = { module = "io.ktor:ktor-client-content-negotiation-jvm", version.ref = "ktorVersion" }
ktor-server-json = { module = "io.ktor:ktor-serialization-kotlinx-json-jvm", version.ref = "ktorVersion" }
ktor-server-test-host = { module = "io.ktor:ktor-server-test-host", version.ref = "ktorVersion" }
ktor-server-di = { module = "io.ktor:ktor-server-di", version.ref = "ktorVersion" }
ktor-server-auth = { module = "io.ktor:ktor-server-auth-jvm", version.ref = "ktorVersion" }
ktor-server-routing-openapi = { module = "io.ktor:ktor-server-routing-openapi-jvm", version.ref = "ktorVersion" }
swagger-annotations = { module = "io.swagger.core.v3:swagger-annotations", version.ref = "swaggerAnnotationsVersion" }
#FP
arrow-core = { module = "io.arrow-kt:arrow-core", version.ref = "arrowVersion" }
arrow-functions = { module = "io.arrow-kt:arrow-functions", version.ref = "arrowVersion" }

[plugins]
kotlinPluginSerialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
kspPlugin = { id = "com.google.devtools.ksp", version.ref = "kspVersion" }
ktorPlugin = { id = "io.ktor.plugin", version.ref = "ktorVersion" }
publishPlugin = { id = "com.vanniktech.maven.publish", version.ref = "publishPluginVersion" }